INSERT INTO `countries`(`id`, `country`) VALUES (null,'Afganistán');
INSERT INTO `countries`(`id`, `country`) VALUES (null, 'Albania');





INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Alemania');


INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Andorra');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Angola');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Anguilla');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Antártida');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Antigua y Barbuda');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Antillas Holandesas');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Arabia Saudí');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Argelia');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Argentina');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Armenia');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Aruba');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'ARY Macedonia');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Australia');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Austria');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Azerbaiyán');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Bahamas');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Bahréin');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Bangladesh');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Barbados');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Bélgica');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Belice');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Benin');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Bermudas');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Bhután');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Bielorrusia');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Bolivia');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Bosnia y Herzegovina');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Botsuana');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Brasil');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Brunéi');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Bulgaria');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Burkina Faso');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Burundi');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Cabo Verde');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Camboya');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Camerún');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Canadá');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Chad');
INSERT INTO `countries` (`id`, `country`) VALUES (null, 'Chile');
INSERT INTO `countries` VALUES(null, 'China');
INSERT INTO `countries` VALUES(null, 'Chipre');
INSERT INTO `countries` VALUES(null, 'Ciudad del Vaticano');
INSERT INTO `countries` VALUES(null, 'Colombia');
INSERT INTO `countries` VALUES(null, 'Comoras');
INSERT INTO `countries` VALUES(null, 'Congo');
INSERT INTO `countries` VALUES(null, 'Corea del Norte');
INSERT INTO `countries` VALUES(null, 'Corea del Sur');
INSERT INTO `countries` VALUES(null, 'Costa de Marfil');
INSERT INTO `countries` VALUES(null, 'Costa Rica');
INSERT INTO `countries` VALUES(null, 'Croacia');
INSERT INTO `countries` VALUES(null, 'Cuba');
INSERT INTO `countries` VALUES(null, 'Dinamarca');
INSERT INTO `countries` VALUES(null, 'Dominica');
INSERT INTO `countries` VALUES(null, 'Ecuador');
INSERT INTO `countries` VALUES(null, 'Egipto');
INSERT INTO `countries` VALUES(null, 'El Salvador');
INSERT INTO `countries` VALUES(null, 'Emiratos Árabes Unidos');
INSERT INTO `countries` VALUES(null, 'Eritrea');
INSERT INTO `countries` VALUES(null, 'Eslovaquia');
INSERT INTO `countries` VALUES(null, 'Eslovenia');
INSERT INTO `countries` VALUES(null, 'España');
INSERT INTO `countries` VALUES(null, 'Estados Unidos');
INSERT INTO `countries` VALUES(null, 'Estonia');
INSERT INTO `countries` VALUES(null, 'Etiopía');
INSERT INTO `countries` VALUES(null, 'Filipinas');
INSERT INTO `countries` VALUES(null, 'Finlandia');
INSERT INTO `countries` VALUES(null, 'Fiyi');
INSERT INTO `countries` VALUES(null, 'Francia');
INSERT INTO `countries` VALUES(null, 'Gabón');
INSERT INTO `countries` VALUES(null, 'Gambia');
INSERT INTO `countries` VALUES(null, 'Georgia');
INSERT INTO `countries` VALUES(null, 'Ghana');
INSERT INTO `countries` VALUES(null, 'Gibraltar');
INSERT INTO `countries` VALUES(null, 'Granada');
INSERT INTO `countries` VALUES(null, 'Grecia');
INSERT INTO `countries` VALUES(null, 'Groenlandia');
INSERT INTO `countries` VALUES(null, 'Guadalupe');
INSERT INTO `countries` VALUES(null, 'Guam');
INSERT INTO `countries` VALUES(null, 'Guatemala');
INSERT INTO `countries` VALUES(null, 'Guayana Francesa');
INSERT INTO `countries` VALUES(null, 'Guinea Ecuatorial');
INSERT INTO `countries` VALUES(null, 'Guinea');
INSERT INTO `countries` VALUES(null, 'Guinea-Bissau');
INSERT INTO `countries` VALUES(null, 'Guyana');
INSERT INTO `countries` VALUES(null, 'Haití');
INSERT INTO `countries` VALUES(null, 'Honduras');
INSERT INTO `countries` VALUES(null, 'Hong Kong');
INSERT INTO `countries` VALUES(null, 'Hungría');
INSERT INTO `countries` VALUES(null, 'India');
INSERT INTO `countries` VALUES(null, 'Indonesia');
INSERT INTO `countries` VALUES(null, 'Irán');
INSERT INTO `countries` VALUES(null, 'Iraq');
INSERT INTO `countries` VALUES(null, 'Irlanda');
INSERT INTO `countries` VALUES(null, 'Isla Bouvet');
INSERT INTO `countries` VALUES(null, 'Isla de Navidad');
INSERT INTO `countries` VALUES(null, 'Isla Norfolk');
INSERT INTO `countries` VALUES(null, 'Islandia');
INSERT INTO `countries` VALUES(null, 'Islas Caimán');
INSERT INTO `countries` VALUES(null, 'Islas Cocos');
INSERT INTO `countries` VALUES(null, 'Islas Cook');
INSERT INTO `countries` VALUES(null, 'Islas Feroe');
INSERT INTO `countries` VALUES(null, 'Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO `countries` VALUES(null, 'Islas Gland');
INSERT INTO `countries` VALUES(null, 'Islas Heard y McDonald');
INSERT INTO `countries` VALUES(null, 'Islas Malvinas');
INSERT INTO `countries` VALUES(null, 'Islas Marianas del Norte');
INSERT INTO `countries` VALUES(null, 'Islas Marshall');
INSERT INTO `countries` VALUES(null, 'Islas Pitcairn');
INSERT INTO `countries` VALUES(null, 'Islas Salomón');
INSERT INTO `countries` VALUES(null, 'Islas Turcas y Caicos');
INSERT INTO `countries` VALUES(null, 'Islas ultramarinas de Estados Unidos');
INSERT INTO `countries` VALUES(null, 'Islas Vírgenes Británicas');
INSERT INTO `countries` VALUES(null, 'Islas Vírgenes de los Estados Unidos');
INSERT INTO `countries` VALUES(null, 'Israel');
INSERT INTO `countries` VALUES(null, 'Italia');
INSERT INTO `countries` VALUES(null, 'Jamaica');
INSERT INTO `countries` VALUES(null, 'Japón');
INSERT INTO `countries` VALUES(null, 'Jordania');
INSERT INTO `countries` VALUES(null, 'Kazajstán');
INSERT INTO `countries` VALUES(null, 'Kenia');
INSERT INTO `countries` VALUES(null, 'Kirguistán');
INSERT INTO `countries` VALUES(null, 'Kiribati');
INSERT INTO `countries` VALUES(null, 'Kuwait');
INSERT INTO `countries` VALUES(null, 'Laos');
INSERT INTO `countries` VALUES(null, 'Lesotho');
INSERT INTO `countries` VALUES(null, 'Letonia');
INSERT INTO `countries` VALUES(null, 'Líbano');
INSERT INTO `countries` VALUES(null, 'Liberia');
INSERT INTO `countries` VALUES(null, 'Libia');
INSERT INTO `countries` VALUES(null, 'Liechtenstein');
INSERT INTO `countries` VALUES(null, 'Lituania');
INSERT INTO `countries` VALUES(null, 'Luxemburgo');
INSERT INTO `countries` VALUES(null, 'Macao');
INSERT INTO `countries` VALUES(null, 'Madagascar');
INSERT INTO `countries` VALUES(null, 'Malasia');
INSERT INTO `countries` VALUES(null, 'Malawi');
INSERT INTO `countries` VALUES(null, 'Maldivas');
INSERT INTO `countries` VALUES(null, 'Malí');
INSERT INTO `countries` VALUES(null, 'Malta');
INSERT INTO `countries` VALUES(null, 'Marruecos');
INSERT INTO `countries` VALUES(null, 'Martinica');
INSERT INTO `countries` VALUES(null, 'Mauricio');
INSERT INTO `countries` VALUES(null, 'Mauritania');
INSERT INTO `countries` VALUES(null, 'Mayotte');
INSERT INTO `countries` VALUES(null, 'México');
INSERT INTO `countries` VALUES(null, 'Micronesia');
INSERT INTO `countries` VALUES(null, 'Moldavia');
INSERT INTO `countries` VALUES(null, 'Mónaco');
INSERT INTO `countries` VALUES(null, 'Mongolia');
INSERT INTO `countries` VALUES(null, 'Montserrat');
INSERT INTO `countries` VALUES(null, 'Mozambique');
INSERT INTO `countries` VALUES(null, 'Myanmar');
INSERT INTO `countries` VALUES(null, 'Namibia');
INSERT INTO `countries` VALUES(null, 'Nauru');
INSERT INTO `countries` VALUES(null, 'Nepal');
INSERT INTO `countries` VALUES(null, 'Nicaragua');
INSERT INTO `countries` VALUES(null, 'Níger');
INSERT INTO `countries` VALUES(null, 'Nigeria');
INSERT INTO `countries` VALUES(null, 'Niue');
INSERT INTO `countries` VALUES(null, 'Noruega');
INSERT INTO `countries` VALUES(null, 'Nueva Caledonia');
INSERT INTO `countries` VALUES(null, 'Nueva Zelanda');
INSERT INTO `countries` VALUES(null, 'Omán');
INSERT INTO `countries` VALUES(null, 'Países Bajos');
INSERT INTO `countries` VALUES(null, 'Pakistán');
INSERT INTO `countries` VALUES(null, 'Palau');
INSERT INTO `countries` VALUES(null, 'Palestina');
INSERT INTO `countries` VALUES(null, 'Panamá');
INSERT INTO `countries` VALUES(null, 'Papúa Nueva Guinea');
INSERT INTO `countries` VALUES(null, 'Paraguay');
INSERT INTO `countries` VALUES(null, 'Perú');
INSERT INTO `countries` VALUES(null, 'Polinesia Francesa');
INSERT INTO `countries` VALUES(null, 'Polonia');
INSERT INTO `countries` VALUES(null, 'Portugal');
INSERT INTO `countries` VALUES(null, 'Puerto Rico');
INSERT INTO `countries` VALUES(null, 'Qatar');
INSERT INTO `countries` VALUES(null, 'Reino Unido');
INSERT INTO `countries` VALUES(null, 'República Centroafricana');
INSERT INTO `countries` VALUES(null, 'República Checa');
INSERT INTO `countries` VALUES(null, 'República Democrática del Congo');
INSERT INTO `countries` VALUES(null, 'República Dominicana');
INSERT INTO `countries` VALUES(null, 'Reunión');
INSERT INTO `countries` VALUES(null, 'Ruanda');
INSERT INTO `countries` VALUES(null, 'Rumania');
INSERT INTO `countries` VALUES(null, 'Rusia');
INSERT INTO `countries` VALUES(null, 'Sahara Occidental');
INSERT INTO `countries` VALUES(null, 'Samoa Americana');
INSERT INTO `countries` VALUES(null, 'Samoa');
INSERT INTO `countries` VALUES(null, 'San Cristóbal y Nevis');
INSERT INTO `countries` VALUES(null, 'San Marino');
INSERT INTO `countries` VALUES(null, 'San Pedro y Miquelón');
INSERT INTO `countries` VALUES(null, 'San Vicente y las Granadinas');
INSERT INTO `countries` VALUES(null, 'Santa Helena');
INSERT INTO `countries` VALUES(null, 'Santa Lucía');
INSERT INTO `countries` VALUES(null, 'Santo Tomé y Príncipe');
INSERT INTO `countries` VALUES(null, 'Senegal');
INSERT INTO `countries` VALUES(null, 'Serbia y Montenegro');
INSERT INTO `countries` VALUES(null, 'Seychelles');
INSERT INTO `countries` VALUES(null, 'Sierra Leona');
INSERT INTO `countries` VALUES(null, 'Singapur');
INSERT INTO `countries` VALUES(null, 'Siria');
INSERT INTO `countries` VALUES(null, 'Somalia');
INSERT INTO `countries` VALUES(null, 'Sri Lanka');
INSERT INTO `countries` VALUES(null, 'Suazilandia');
INSERT INTO `countries` VALUES(null, 'Sudáfrica');
INSERT INTO `countries` VALUES(null, 'Sudán');
INSERT INTO `countries` VALUES(null, 'Suecia');
INSERT INTO `countries` VALUES(null, 'Suiza');
INSERT INTO `countries` VALUES(null, 'Surinam');
INSERT INTO `countries` VALUES(null, 'Svalbard y Jan Mayen');
INSERT INTO `countries` VALUES(null, 'Tailandia');
INSERT INTO `countries` VALUES(null, 'Taiwán');
INSERT INTO `countries` VALUES(null, 'Tanzania');
INSERT INTO `countries` VALUES(null, 'Tayikistán');
INSERT INTO `countries` VALUES(null, 'Territorio Británico del Océano Índico');
INSERT INTO `countries` VALUES(null, 'Territorios Australes Franceses');
INSERT INTO `countries` VALUES(null, 'Timor Oriental');
INSERT INTO `countries` VALUES(null, 'Togo');
INSERT INTO `countries` VALUES(null, 'Tokelau');
INSERT INTO `countries` VALUES(null, 'Tonga');
INSERT INTO `countries` VALUES(null, 'Trinidad y Tobago');
INSERT INTO `countries` VALUES(null, 'Túnez');
INSERT INTO `countries` VALUES(null, 'Turkmenistán');
INSERT INTO `countries` VALUES(null, 'Turquía');
INSERT INTO `countries` VALUES(null, 'Tuvalu');
INSERT INTO `countries` VALUES(null, 'Ucrania');
INSERT INTO `countries` VALUES(null, 'Uganda');
INSERT INTO `countries` VALUES(null, 'Uruguay');
INSERT INTO `countries` VALUES(null, 'Uzbekistán');
INSERT INTO `countries` VALUES(null, 'Vanuatu');
INSERT INTO `countries` VALUES(null, 'Venezuela');
INSERT INTO `countries` VALUES(null, 'Vietnam');
INSERT INTO `countries` VALUES(null, 'Wallis y Futuna');
INSERT INTO `countries` VALUES(null, 'Yemen');
INSERT INTO `countries` VALUES(null, 'Yibuti');
INSERT INTO `countries` VALUES(null, 'Zambia');
INSERT INTO `countries` VALUES(null, 'Zimbabue');
